### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [kenwheeler/gulp-helper#22]
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version (`4.1.0`) of this package:

1. Requiring `View` from `atom` is no longer supported. Please require `atom-space-pen-views` instead: `{View} = require 'atom-space-pen-views'` Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
1. atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use `atom.views.getView(atom.workspace)`, which returns an HTMLElement.
1. Please use Workspace::addBottomPanel() instead

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see up-to-date deprecations.

If this package has been replaced by another package or functionality in core, please reply with this information.

See https://github.com/atom/atom/issues/6867 for more info. Thanks!

**Comment by cjwilburn** [comment]
@benogle would it be possible for a fork of this to be supported? I use this and know of other folks who do.

**Comment by benogle** [comment]
Yeah, we could point the package store at a fork of this. Though I think we should wait for @kenwheeler a little longer. Looks like this package was updated 17 days ago, so he isnt totally MIA. 

@kenwheeler would you be open to either transferring this repo to @cjwilburn or making him a contributor?

**Comment by cjwilburn** [comment]
<--- (her/she) @benogle. :) Also, I'm cool with waiting for @kenwheeler a bit longer.

**Comment by benogle** [comment]
Oh, I'm a terrible human. Sorry, edited :(

**Comment by cjwilburn** [comment]
No worries. It happens pretty often. Extremely short hair is mostly convenient for the wearer. :)

**Comment by kenwheeler** [comment]
Hey sorry, I'll get this up to date asap

**Comment by petemill** [comment]
I have done the neccessary work for this @cjwilburn @benogle and submitted a PR at https://github.com/kenwheeler/gulp-helper/pull/24. Just waiting on @kenwheeler to integrate or give me write access.

**Comment by sudoforge** [comment]
This should be closed manually, as it wasn't referenced in the commit for #24 and thus never got auto-closed.

**Comment by kenwheeler** [comment]
Sorry @petemill I'll get that merged either tonight or tomorrow

**Comment by sudoforge** [comment]
@kenwheeler It looks like that was already merged -- this issue is just open because it wasn't referenced in the merge.
